name: build-esp32s3-lvgl
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y git build-essential cmake ninja-build ccache flex bison gperf \
            libffi-dev libssl-dev python3 python3-venv python3-pip
      - name: Build mpy-cross
        run: make -C mpy-cross
      - name: ESP-IDF install
        working-directory: ports/esp32
        run: |
          ./esp-idf/install.sh esp32,esp32s3
          echo "source $(pwd)/esp-idf/export.sh" >> $GITHUB_ENV
      - name: Build firmware
        working-directory: ports/esp32
        shell: bash
        run: |
          source ./esp-idf/export.sh
          idf.py set-target esp32s3
          idf.py build -D MICROPY_BOARD=GENERIC_S3 -D USER_C_MODULES=../../../lib/lv_bindings/bundle.cmake
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32s3-lvgl-firmware
          path: |
            ports/esp32/build/micropython.bin
            ports/esp32/build/bootloader/bootloader.bin
            ports/esp32/build/partition_table/partition-table.bin
